### PR TITLE
Fix IllegalStateException: WELD-001578 (Jersey 6000) on JDK 24+.

### LINKED ISSUE #6000: IllegalStateException: WELD-001578 when using Java >=24 with a standalone Jakarta RS server
In our team I have written a test server instance that runs as a standalone server (thanks @mkarg for your excellent articles and tutorials!). The code to startup the server is this (unnecessary parts removed):

```java
@ApplicationPath("/")
public class MyTestserver extends Application implements AutoCloseable {
	(...)

	public CompletionStage<Instance> startServer(MyTestServerProps props) throws GeneralSecurityException, IOException {
		var builder = SeBootstrap.Configuration.builder().host(props.host).rootPath(props.contextRoot).port(props.port);
		if (props.useTls) {
			builder.protocol("HTTPS").sslContext(configureTls(props));
		}

		this.instance = SeBootstrap.start(this, builder.build());
		this.instance.thenAccept(i -> {
			LOG.info("server gestartet");
			LOG.info("- Host:         {}", props.host);
			LOG.info("- Port:         {}", props.port);
			LOG.info("- Context-Root: {}", props.contextRoot);
			LOG.info("- Protocol:    {}", props.useTls ? "HTTPS" : "HTTP");
		});
		return this.instance;
	}

	@Override
	public Set<Class<?>> getClasses() {
		return Set.of(PingApi.class, ...);
	}

	private static SSLContext configureTls(RaxTestServerProps props) throws GeneralSecurityException, IOException {
		KeyManager[] km = ...;
		TrustManager[] tm = ...;
		var ctx = SSLContext.getInstance("TLSv1.2");
		ctx.init(km, tm, null);
		return ctx;
	}
}
```

As you can see, no big magic. The `PingApi` service mentioned in the snippet above is only used to serve as a kind of availability check, i.e. when called via a GET request returns "Hello world":

```java
@Path("/ping")
public class PingApi {
	private @Inject PingService delegate;

	@GET
	@Produces(MediaType.TEXT_PLAIN)
	public @Owning Response ping() {
		return this.delegate.ping();
	}
}
```

```java
public interface PingService {
	String HELLO_WORLD = "Hello world!";

	Response ping();
}
```

```java
@RequestScoped
public class PingServiceImpl implements PingService {
	@Override
	public @Owning Response ping() {
		Package pkg = getClass().getPackage();
		String str = HELLO_WORLD //
				+ "\n\nImplementation-Title:   " + pkg.getImplementationTitle() //
				+ "\nImplementation-Version: " + pkg.getImplementationVersion() //
				+ "\nImplementation-Vendor:  " + pkg.getImplementationVendor();

		return Response.ok().entity(str).build();
	}
}
```

The rest of the REST resources offered by the server are implemented similar, i.e. implementation agnostic. I have tested the server code with Jersey 3.1.11 and RESTeasy 6.2.14.Final as Jakarta RS implementation under Java 21, everything works.

Using Java 23, everything works, but with Java >=24 I get the following exception when calling the /ping request with Jersey:

```
Sept. 29, 2025 12:10:04 PM org.glassfish.jersey.server.ServerRuntime$Responder process
WARNUNG: An exception mapping did not successfully produce and processed a response. Logging the exception propagated to the default exception mapper.
org.jboss.weld.exceptions.IllegalStateException: WELD-001578: WeldDefaultProxyServices failed to load/define a class with name org.glassfish.jersey.internal.util.collection.Ref$1394199392$Proxy$_$$_WeldClientProxy whose original class was class java.lang.Object because all attempts to determine a class loader ended with null.
        at org.jboss.weld.bean.proxy.util.WeldDefaultProxyServices.loadClass(WeldDefaultProxyServices.java:79)
        at org.jboss.weld.bean.proxy.ProxyFactory.getProxyClass(ProxyFactory.java:412)
        at org.jboss.weld.bean.proxy.ProxyFactory.instantiateProxy(ProxyFactory.java:375)
        at org.jboss.weld.bean.proxy.ProxyFactory.create(ProxyFactory.java:368)
        at org.jboss.weld.bean.proxy.ClientProxyFactory.create(ClientProxyFactory.java:84)
        at org.jboss.weld.bean.proxy.ClientProxyProvider.createClientProxy(ClientProxyProvider.java:207)
        at org.jboss.weld.bean.proxy.ClientProxyProvider.createClientProxy(ClientProxyProvider.java:197)
        at org.jboss.weld.bean.proxy.ClientProxyProvider$CreateClientProxy.apply(ClientProxyProvider.java:52)
        at org.jboss.weld.bean.proxy.ClientProxyProvider$CreateClientProxy.apply(ClientProxyProvider.java:48)
        at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.lambda$new$0(ReentrantMapBackedComputingCache.java:57)
        at org.jboss.weld.util.LazyValueHolder$1.computeValue(LazyValueHolder.java:32)
        at org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:46)
        at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:74)
        at org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getCastValue(ReentrantMapBackedComputingCache.java:80)
        at org.jboss.weld.bean.proxy.ClientProxyProvider.getClientProxy(ClientProxyProvider.java:232)
        at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:720)
        at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:746)
        at org.jboss.weld.util.ForwardingBeanManager.getReference(ForwardingBeanManager.java:65)
        at org.jboss.weld.bean.builtin.BeanManagerProxy.getReference(BeanManagerProxy.java:89)
        at org.glassfish.jersey.inject.cdi.se.CdiSeInjectionManager.getInstanceInternal(CdiSeInjectionManager.java:178)
        at org.glassfish.jersey.inject.cdi.se.CdiSeInjectionManager.getInstance(CdiSeInjectionManager.java:166)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.lambda$service$0(GrizzlyHttpContainer.java:364)
        at org.glassfish.jersey.server.internal.process.ReferencesInitializer.apply(ReferencesInitializer.java:61)
        at org.glassfish.jersey.server.internal.process.ReferencesInitializer.apply(ReferencesInitializer.java:31)
        at org.glassfish.jersey.process.internal.Stages$LinkedStage.apply(Stages.java:284)
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:173)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:266)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:253)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:696)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190)
        at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:291)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:456)

Sept. 29, 2025 12:10:04 PM org.glassfish.jersey.server.ServerRuntime$Responder writeResponse
SCHWERWIEGEND: Error while closing the output stream in order to commit response.
java.lang.IllegalStateException: Illegal attempt to call getOutputStream() after getWriter() has already been called.
        at org.glassfish.grizzly.http.server.Response.getNIOOutputStream(Response.java:578)
        at org.glassfish.grizzly.http.server.Response.getOutputStream(Response.java:602)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer$ResponseWriter.writeResponseStatusAndHeaders(GrizzlyHttpContainer.java:250)
        at org.glassfish.jersey.server.ServerRuntime$Responder$1.getOutputStream(ServerRuntime.java:681)
        at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:174)
        at org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:279)
        at org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:235)
        at org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:250)
        at org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:569)
        at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:406)
        at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:763)
        at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:398)
        at org.glassfish.jersey.server.ServerRuntime$Responder.processResponseWithDefaultExceptionMapper(ServerRuntime.java:647)
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:475)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:282)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:253)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:696)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190)
        at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:291)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:456)
```

However, switching to RESTeasy 6.2.14 everything still works, even with Java 25.

Does anyone know what is causing this exception? Am I missing something when starting up the server code?

### PR DESCRIPTION
**Pull request by jansupol**

### CODE REVIEW

**Review by senivam — APPROVED** [review]

File: incubator/cdi-inject-weld/src/main/java/org/glassfish/jersey/inject/weld/internal/bean/JerseyBean.java [hunk 1]
```diff
@@ -172,7 +172,7 @@ public int getRank() {
 
     @Override
     public Class<?> getBeanClass() {
-        return Object.class;
+        return getClass();
```
Comment (jbescos) [inline incubator/cdi-inject-weld/src/main/java/org/glassfish/jersey/inject/weld/internal/bean/JerseyBean.java:175]: Why does this fix the issue?. Is it related to modules?.

Comment (jansupol) [reply incubator/cdi-inject-weld/src/main/java/org/glassfish/jersey/inject/weld/internal/bean/JerseyBean.java:175]: It relates to classloading. Weld tries to get classloader or context classloader from Object.class, but with JDK 24 it returns null.

**Review by jbescos — APPROVED** [review]

File: incubator/cdi-inject-weld/src/main/java/org/glassfish/jersey/inject/weld/internal/bean/JerseyBean.java (hunk 1 above)
Comment (jbescos) [reply incubator/cdi-inject-weld/src/main/java/org/glassfish/jersey/inject/weld/internal/bean/JerseyBean.java:175]: I was asking because `Thread.currentThread().getContextClassLoader()` was returning null too. I couldn't figure out why.

Comment (jansupol) [reply incubator/cdi-inject-weld/src/main/java/org/glassfish/jersey/inject/weld/internal/bean/JerseyBean.java:175]: The `Object.class` was not exactly aligned with the method javadoc.
