### PR TITLE
For OSGi services lookup use only classes assignable from service class

### LINKED ISSUE #5036: ClassCastException if loaded by different class loaders in OSGi runtime
## Description

Our code (Eclipse plugin) using Jersey client is running in OSGi runtime (Eclipse IDE). There are some Eclipse platforms that contain version of Jersey libraries different from that required by our plugin. Therefore our plugin puts the required version to the classpath. However, each Jersey version is then loaded by a different class loader. There are two places where this is causing problems:

- lookup of the `InjectionManagerFactory` in `org.glassfish.jersey.internal.inject.Injections`
- configuring of auto discoverable providers in  `org.glassfish.jersey.model.internal.CommonConfig`

The problem is that in those places and in this scenario, cast is done using classes from different class loaders resulting in `ClassCastException` stopping the request completely. We think these casts could be avoided and the request should be able to proceed. 

### Lookup of the InjectionManagerFactory

Note: _I have truncated the exception stack trace to show only the Jersey stuff because it is quite long with all the Eclipse stuff._

Exception:

```
java.lang.ClassCastException: class org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory cannot be cast to class org.glassfish.jersey.internal.inject.InjectionManagerFactory (org.glassfish.jersey.inject.hk2.Hk2InjectionManagerFactory is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @381dbeba; org.glassfish.jersey.internal.inject.InjectionManagerFactory is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1d49806)
	at org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:74) ~[org.glassfish.jersey.core.jersey-common_3.0.4.jar:?]
	at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:44) ~[org.glassfish.jersey.core.jersey-common_3.0.4.jar:?]
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:413) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317) ~[org.glassfish.jersey.core.jersey-common_3.0.4.jar:?]
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:820) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:176) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.ClientRequest.getInjectionManager(ClientRequest.java:567) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:371) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:206) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:38) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at com.ca.endevor.service.EndevorServiceRest$DatasourceAuth.getAsJson(EndevorServiceRest.java:525) ~[com.ca.endevor.uiProject/:?]
```

 Code snippet:
https://github.com/eclipse-ee4j/jersey/blob/8f7fa9917626095a816dc2114a5c1e99a89ea11b/core-common/src/main/java/org/glassfish/jersey/internal/inject/Injections.java#L72-L93

### Configuring of AutoDiscoverable

Note: _I have truncated the exception stack trace to show only the Jersey stuff because it is quite long with all the Eclipse stuff._

Exception:

```
java.lang.ClassCastException: class org.glassfish.jersey.server.wadl.internal.WadlAutoDiscoverable cannot be cast to class org.glassfish.jersey.internal.spi.AutoDiscoverable (org.glassfish.jersey.server.wadl.internal.WadlAutoDiscoverable is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @654b2ed4; org.glassfish.jersey.internal.spi.AutoDiscoverable is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @55bc4134)
	at java.util.TreeMap.put(TreeMap.java:787) ~[?:?]
	at java.util.TreeMap.put(TreeMap.java:534) ~[?:?]
	at java.util.TreeSet.add(TreeSet.java:255) ~[?:?]
	at java.util.AbstractCollection.addAll(AbstractCollection.java:336) ~[?:?]
	at java.util.TreeSet.addAll(TreeSet.java:310) ~[?:?]
	at org.glassfish.jersey.model.internal.CommonConfig.configureAutoDiscoverableProviders(CommonConfig.java:609) ~[org.glassfish.jersey.core.jersey-common_3.0.4.jar:?]
	at org.glassfish.jersey.client.ClientConfig$State.configureAutoDiscoverableProviders(ClientConfig.java:384) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:439) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317) ~[org.glassfish.jersey.core.jersey-common_3.0.4.jar:?]
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:820) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:176) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.ClientRequest.getInjectionManager(ClientRequest.java:567) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:371) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:206) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:38) ~[org.glassfish.jersey.core.jersey-client_3.0.4.jar:?]
	at com.ca.endevor.service.EndevorServiceRest$DatasourceAuth.getAsJson(EndevorServiceRest.java:524) ~[com.ca.endevor.uiProject/:?]
```

Code snippet:

https://github.com/eclipse-ee4j/jersey/blob/8f7fa9917626095a816dc2114a5c1e99a89ea11b/core-common/src/main/java/org/glassfish/jersey/model/internal/CommonConfig.java#L582-L629

## Suggested solution

I have tested a solution with our code that will simply check in both places if the cast can be done. Do you think the suggested solution is OK? Or is there some other way to solve this situation? 
I can open a PR if you think the solution is OK.

### PR DESCRIPTION
**Pull request by mmeldo**
Closes #5036 
Prevent a situation when the provider class cannot be cast to service class by checking if the service class is assignable from the provider class.

### CODE REVIEW

**Review by senivam — APPROVED** [review]
LGTM

**Review by jbescos — APPROVED** [review]

File: core-common/src/main/java/org/glassfish/jersey/internal/OsgiRegistry.java [hunk 1]
```diff
@@ -552,14 +552,18 @@ private void register(final Bundle bundle) {
...
             for (final Map<String, Callable<List<Class<?>>>> value : factories.values()) {
-                if (value.containsKey(serviceName)) {
+                if (value.containsKey(serviceClass.getName())) {
                     try {
-                        result.addAll(value.get(serviceName).call());
+                        for (final Class<?> clazz : value.get(serviceClass.getName()).call()) {
+                            if (serviceClass.isAssignableFrom(clazz)) {
+                                result.add(clazz);
+                            }
+                        }
```
Comment (jansupol) [inline core-common/src/main/java/org/glassfish/jersey/internal/OsgiRegistry.java:566]: is it possible to warn about the classes that are not loaded? Something like:
```
else {
   CodeSource src = serviceClass.getProtectionDomain().getCodeSource();
   if (src != null) {
       Logger.log(Level.FINE, "class {0} was not registered to OSGi", src.getLocation() + "!" + serviceClass.getName());
   } else {
       Logger.log(Level.FINE, "class {0} was not registered to OSGi", serviceClass.getName());
   }
}
```

Comment (mmeldo) [reply core-common/src/main/java/org/glassfish/jersey/internal/OsgiRegistry.java:566]: No problem. I was thinking about that, but was not sure how often the `ServiceFinder.find` is used so did not want to spam logs.
And I guess I will use lower debug level (FINER).

Comment (mmeldo) [reply core-common/src/main/java/org/glassfish/jersey/internal/OsgiRegistry.java:570]: Had to get rid of the `Class.getModule()` from the log message since it is not available in Java 8. But now, to get more info for the message, one would have to get it from the factory (`BundleSpiProvidersLoader`) bundle which I am not sure is worth it.

Comment (jansupol) [reply core-common/src/main/java/org/glassfish/jersey/internal/OsgiRegistry.java:570]: The information from `CodeSource` would be nice, but I admit that OSGi env could have `CodeSource` null.

**Review by jansupol — APPROVED** [review]

**Review by jbescos — APPROVED** [review]
