### PR TITLE
Multirelease includes JDK21 to support Thread.isVirtual()

### LINKED ISSUE #5623: Carrier Thread pinning on stack CommittingOutputStream.flushBuffer()
We are running tests for sample application with Helidon 4.x based on Loom virtual threads  with JDK 21  in the Kubernetes containers.   When running load test with concurrent users we see that application hangs and JVM becomes unresponsive 
we do not see any resource  issues for CPU, Memory, Heap etc.. The usage are  much below the configured capacity. 

In JFR, we do seeing large number of carrier thread pinning on the  below stack.   The pinning is happening when the. org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer() is invoking ByteArrayOutputStream.writeTo().

stack snippet below from tracePinnedThreads output:

io.helidon.webserver.observe.tracing.TracingObserver$TracingStreamOutputDelegate.write(TracingObserver.java:525)
**java.base/java.io.ByteArrayOutputStream.writeTo(ByteArrayOutputStream.java:163) <== monitors:1** 
**org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:278)**    org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:232)   org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:247)   org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:865)   org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:403)

 The recommendation from teh JDK team was to  modify the implementation of "org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer()" to  avoid calling the synchronised  method. ByteArrayOutputStream.writeTo()

Based on the suggestion, the below code change was tried out, in the implementation of CommittingOutputStream.flushBuffer()

private void flushBuffer(boolean endOfStream) throws IOException {
             .........
             ............ 
            if (buffer != null && adaptedOutput != null) {
                //buffer.writeTo(adaptedOutput);
                adaptedOutput.write(buffer.toByteArray());
            }
        }
    }

With this change, we no longer see the carrier thread pinning on this stack.
The ask is to see if this code change can be implemented in Jersey.

### PR DESCRIPTION
**Pull request by jansupol**

### CODE REVIEW

**Review by senivam — APPROVED** [review]

File: core-common/src/main/java/org/glassfish/jersey/message/internal/CommittingOutputStream.java [hunk 1]
```diff
@@ -59,7 +59,7 @@
 public final class CommittingOutputStream extends OutputStream {
 
     private static final Logger LOGGER = Logger.getLogger(CommittingOutputStream.class.getName());
-    private static final boolean JDK_21 = JdkVersion.getJdkVersion().getMajor() > 20;
+    private final boolean isVirtualThread = VirtualThreadSupport.isVirtualThread();
```
Comment (jbescos) [inline core-common/src/main/java/org/glassfish/jersey/message/internal/CommittingOutputStream.java:62]: I am just curious, was there any issue with the next line?:
`private static final boolean JDK_21 = JdkVersion.getJdkVersion().getMajor() > 20;`

**Review by jbescos — APPROVED** [review]

**Review by jbescos — APPROVED** [review]
