### PR TITLE
Ensure the RequestScope and other singleton bindings are registered just once

### LINKED ISSUE #5618: Injection error when using a `DynamicFeature`
Recently we have received an [issue at dropwizard](https://github.com/dropwizard/dropwizard/issues/8455) with a strange behavior regarding Jersey dependency injection. I've now reproduced this issue with Jersey-related classes only to exclude a dropwizard issue. The problem can be observed with the following `ContainerRequestFilter`:

```java
public static class InjectedFilter implements ContainerRequestFilter {
    @Inject
    private InjectionManager injectionManager;
    @Override
    public void filter(ContainerRequestContext requestContext) throws IOException {
        Ref<HttpServletRequest> requestRef = injectionManager.getInstance((new GenericType<Ref<HttpServletRequest>>() {}).getType());
        if (requestRef == null || requestRef.get() == null) {
            throw new IllegalStateException("Request not injected");
        }
    }
}
```

When registering this filter directly to the `ResourceConfig` as a `Class` like `resourceConfig.register(InjectedFilter.class)` the filter works fine and the `Ref<HttpServletRequest>` holds the current request.

However, when registering this filter through the `FeatureContext` of a `DynamicFeature`, HK2 throws an exception:
```
MultiException stack 1 of 2
java.lang.IllegalStateException: There is more than one active context for org.glassfish.jersey.process.internal.RequestScoped
	at org.jvnet.hk2.internal.ServiceLocatorImpl._resolveContext(ServiceLocatorImpl.java:2222)
...
MultiException stack 2 of 2
java.lang.IllegalStateException: While attempting to create a service for SystemDescriptor(
	implementation=org.glassfish.jersey.inject.hk2.InstanceSupplierFactoryBridge
	contracts={org.glassfish.jersey.internal.util.collection.Ref}
	scope=org.glassfish.jersey.process.internal.RequestScoped
	qualifiers={}
	descriptorType=PROVIDE_METHOD
	descriptorVisibility=NORMAL
	metadata=
	rank=0
	loader=org.glassfish.hk2.utilities.binding.AbstractBinder$2@6e59af3d
	proxiable=null
	proxyForSameScope=null
	analysisName=null
	id=23
	locatorId=0
	identityHashCode=239875089
	reified=true) in scope org.glassfish.jersey.process.internal.RequestScoped an error occured while locating the context
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2093)
```

Here is a Jersey test case to reproduce the behavior:

```java
public class InjectionTest extends JerseyTest {
    @Path("hello")
    public static class HelloResource {
        @GET
        public String getHello() {
            return "Hello World!";
        }
    }
    @Override
    protected Application configure() {
        ResourceConfig resourceConfig = new ResourceConfig(HelloResource.class);
        resourceConfig.register(new InjectedFilterRegistrar(InjectedFilter.class));
        return resourceConfig;
    }
    @Override
    protected TestContainerFactory getTestContainerFactory() throws TestContainerException {
        return new JettyTestContainerFactory();
    }
    @Test
    public void test() {
        final String hello = target("hello").request().get(String.class);
        assertEquals("Hello World!", hello);
    }
    public static class InjectedFilter implements ContainerRequestFilter {
        @Inject
        private InjectionManager injectionManager;
        @Override
        public void filter(ContainerRequestContext requestContext) throws IOException {
            Ref<HttpServletRequest> requestRef = injectionManager.getInstance((new GenericType<Ref<HttpServletRequest>>() {}).getType());
            if (requestRef == null || requestRef.get() == null) {
                throw new IllegalStateException("Request not injected");
            }
        }
    }
    public static class InjectedFilterRegistrar implements DynamicFeature {
        private final Class<?> filterToRegister;
        public InjectedFilterRegistrar(Class<?> filterToRegister) {
            this.filterToRegister = filterToRegister;
        }
        @Override
        public void configure(ResourceInfo resourceInfo, FeatureContext context) {
            context.register(filterToRegister);
        }
    }
}
```

### PR DESCRIPTION
**Pull request by jansupol**

### CODE REVIEW

**Review by senivam — APPROVED** [review]

File: tests/e2e/src/test/java/org/glassfish/jersey/tests/e2e/inject/SingleRequestScopeInjectionTest.java [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+    }
+    public static class InjectedFilterRegistrar implements DynamicFeature {
+        private final Class<?> filterToRegister;
+        private final AtomicInteger ai = new AtomicInteger(0);
+        public InjectedFilterRegistrar(Class<?> filterToRegister) {
+            this.filterToRegister = filterToRegister;
+        }
+        @Override
+        public void configure(ResourceInfo resourceInfo, FeatureContext context) {
+            if (ai.get() == 1) {
```
Comment (jbescos) [inline tests/e2e/src/test/java/org/glassfish/jersey/tests/e2e/inject/SingleRequestScopeInjectionTest.java]: I don't understand it, when is `ai` incremented?.

Comment (jansupol) [reply tests/e2e/src/test/java/org/glassfish/jersey/tests/e2e/inject/SingleRequestScopeInjectionTest.java]: Ha, nice catch. I had `System.out.println(ai.incrementAndGet())` before when testing, and I did not want to have messages in the test, dropping the line :)

**Review by jbescos — APPROVED** [review]

**Review by senivam — APPROVED** [review]
