### PR TITLE
SSE Flow.Subscriber injectable as event sink

### LINKED ISSUE #4500: JerseyEventSink shouln't throw exceptions in Flow.Subscriber methods
[JerseyEventSink](https://github.com/eclipse-ee4j/jersey/blob/8dcbaf4b5cb0fb345eb949acfa66b1fbe09d1ffb/media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java) throws `IllegalStateException` from `Flow.Subscriber` methods which is not spec compliant [2.13](https://github.com/reactive-streams/reactive-streams-jvm#2.13). Client side closing the connection should be propagated to upstream by `Flow.Subscription.cancel()`

### LINKED ISSUE #4501: SSE Endpoint should be able to inject Flow.Subscriber
It would be great if Jersey could inject Flow.Subscriber directly, its implemented by `JerseyEventSink`.
```java
    @GET
    @Path("sse")
    @Produces(MediaType.SERVER_SENT_EVENTS)
    public void listenToEvents(@Context Flow.Subscriber<String> eventSink) {
```

### PR DESCRIPTION
**Pull request by danielkec**
Fixes #4501 
Fixes #4500

## Now its possible in Java 11+
```java
    @GET
    @Path("sse")
    @Produces(MediaType.SERVER_SENT_EVENTS)
    public void listenToEvents(@Context java.util.concurrent.Flow.Subscriber<String> eventSink)
    public void listenToEvents(@Context java.util.concurrent.Flow.Subscriber<OutboundEvent> eventSink)
    public void listenToEvents(@Context org.glassfish.jersey.internal.jsr166.Flow.Subscriber<String> eventSink)
    public void listenToEvents(@Context org.glassfish.jersey.internal.jsr166.Flow.Subscriber<OutboundEvent> eventSink)
```

## Java 8
```java
    @GET
    @Path("sse")
    @Produces(MediaType.SERVER_SENT_EVENTS)
    public void listenToEvents(@Context org.glassfish.jersey.internal.jsr166.Flow.Subscriber<String> eventSink)
    public void listenToEvents(@Context org.glassfish.jersey.internal.jsr166.Flow.Subscriber<OutboundEvent> eventSink)
```

### CODE REVIEW

File: core-common/src/main/java11/org/glassfish/jersey/internal/jsr166/SubmissionPublisher.java [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.
+ * Copyright (c) 2020 Oracle and/or its affiliates. All rights reserved.
```
Comment (tomas-langer) [inline core-common/src/main/java11/org/glassfish/jersey/internal/jsr166/SubmissionPublisher.java:2]: Change to this file seems unnecessary.

Comment (danielkec) [reply core-common/src/main/java11/org/glassfish/jersey/internal/jsr166/SubmissionPublisher.java]: fixed

File: core-server/src/main/java/org/glassfish/jersey/server/ChunkedOutput.java [hunk 2]
```diff
@@ -290,6 +290,7 @@ public Void call() throws IOException {
         } finally {
             if (closed) {
                 try {
+                    closeByClient();
                     responseContext.close();
```
Comment (danielkec) [inline core-server/src/main/java/org/glassfish/jersey/server/ChunkedOutput.java:294]: @jansupol Is this proper way to propagate close from client to JerseyEventSink?

File: core-server/src/main/java/org/glassfish/jersey/server/model/internal/SseTypeResolver.java [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+
+    private static final Set<Class<?>> SUPPORTED_SSE_SINK_TYPES;
+
+    static {
+        Set<Class<?>> set = new HashSet<>(8);
+
+        set.add(org.glassfish.jersey.internal.jsr166.Flow.Subscriber.class);
+        set.add(javax.ws.rs.sse.SseEventSink.class);
+        try {
+            Class<?> clazz = Class.forName("java.util.concurrent.Flow.Subscriber");
```
Comment (jansupol) [inline core-server/src/main/java/org/glassfish/jersey/server/model/internal/SseTypeResolver.java:17]: clazz = AccessController.doPrivileged(ReflectionHelper.classForNamePA("java.util.concurrent.Flow.Subscriber", null)

File: core-server/src/main/java/org/glassfish/jersey/server/model/internal/SseTypeResolver.java [hunk 4]
```diff
@@ -0,0 +1,28 @@
+package org.glassfish.jersey.server.model.internal;
+
+import java.util.Collections;
+import java.util.HashSet;
+import java.util.Set;
+
+public class SseTypeResolver {
```
Comment (jansupol) [inline core-server/src/main/java/org/glassfish/jersey/server/model/internal/SseTypeResolver.java:7]: Please make it final with private constructor

File: core-server/src/main/java/org/glassfish/jersey/server/ChunkedOutput.java (hunk 2 above)
Comment (jansupol) [reply core-server/src/main/java/org/glassfish/jersey/server/ChunkedOutput.java:294]: how about to name it `ònClose()`?

File: media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java [hunk 5]
```diff
@@ -39,55 +45,109 @@
...
 
     @Override
     public void onError(final Throwable throwable) {
-        checkClosed();
         if (throwable == null) {
             throw new NullPointerException(LocalizationMessages.PARAM_NULL("throwable"));
         }
-        subscription.cancel();
+        try {
+            super.close();
```
Comment (jansupol) [inline media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java:133]: how about calling this.close()? Same as onComplete? Would you still need the onClose()?

File: core-server/src/main/java/org/glassfish/jersey/server/ChunkedOutput.java (hunk 2 above)
Comment (danielkec) [reply core-server/src/main/java/org/glassfish/jersey/server/ChunkedOutput.java]: fixed

File: core-server/src/main/java/org/glassfish/jersey/server/model/internal/SseTypeResolver.java (hunk 4 above)
Comment (danielkec) [reply core-server/src/main/java/org/glassfish/jersey/server/model/internal/SseTypeResolver.java]: fixed

File: media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java (hunk 5 above)
Comment (danielkec) [reply media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java:133]: Intention was differentiate client side close(disconnect) where `cancel` is expected, from upstream close where `cancel` is not desirable as upstream is cause of closing. Change should avoid similar issues as oracle/helidon/issues/806 in the future.

File: core-server/src/main/java/org/glassfish/jersey/server/model/internal/SseTypeResolver.java (hunk 3 above)
Comment (danielkec) [reply core-server/src/main/java/org/glassfish/jersey/server/model/internal/SseTypeResolver.java]: thx fixed

File: media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java [hunk 6]
```diff
@@ -118,15 +180,30 @@ public void flush() throws IOException {
...
-    public void onComplete() {
-        checkClosed();
-        subscription.cancel();
-        close();
+    @Override
+    protected void onClose(Exception e) {
+        cancelUpstream();
+    }
+
+    private void cancelUpstream() {
```
Comment (jansupol) [inline media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java:188]: Can you name this cancelSubscription()?

**Review by jansupol — CHANGES_REQUESTED** [review]

File: media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java [hunk 7]
```diff
@@ -39,55 +45,109 @@
...
+            } else {
+                // implicit wrapping
+                // TODO: Jersey annotation for explicit media type
+                write(new OutboundEvent.Builder()
+                        .mediaType(implicitType)
+                        .data(item)
+                        .build());
+            }
+        } catch (final Throwable e) {
+            LOGGER.log(Level.INFO, LocalizationMessages.EVENT_SOURCE_DEFAULT_ONERROR(), e);
```
[the remark this answers is not in the document]
Comment (danielkec) [reply media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java:123]: There can be also Runtime exception propagated from flushQueue, specs forbids Subscriber from throwing anything else than NPE from onNext

[the remark this answers is not in the document]
Comment (danielkec) [reply media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java:123]: This time I have checked to be sure 😁 https://github.com/reactive-streams/reactive-streams-jvm#2.13

File: core-server/src/main/java/org/glassfish/jersey/server/model/internal/SseTypeResolver.java [hunk 8]
```diff
@@ -0,0 +1,34 @@
+package org.glassfish.jersey.server.model.internal;
```
[the remark this answers is not in the document]
Comment (danielkec) [reply core-server/src/main/java/org/glassfish/jersey/server/model/internal/SseTypeResolver.java:16]: added

File: media/sse/src/test/java/org/glassfish/jersey/media/sse/JerseyFlowAdapters.java [hunk 9]
```diff
@@ -0,0 +1,64 @@
+/*
```
[the remark this answers is not in the document]
Comment (danielkec) [reply media/sse/src/test/java/org/glassfish/jersey/media/sse/JerseyFlowAdapters.java]: moved

File: tests/integration/reactive-streams/sse/tck-suite.xml [hunk 10]
```diff
@@ -0,0 +1,28 @@
+<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
+<!--
+
+    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.
```
[the remark this answers is not in the document]
Comment (danielkec) [reply tests/integration/reactive-streams/sse/tck-suite.xml]: fixed

File: media/sse/pom.xml [hunk 11]
```diff
@@ -56,6 +56,34 @@
             <type>pom</type>
             <scope>test</scope>
         </dependency>
+        <dependency>
```
[the remark this answers is not in the document]
Comment (danielkec) [reply media/sse/pom.xml]: updated

File: media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java [hunk 12]
```diff
@@ -118,15 +180,30 @@ public void flush() throws IOException {
...
+            cancelUpstream();
             throw new IllegalStateException(LocalizationMessages.EVENT_SOURCE_ALREADY_CLOSED());
         }
     }
+
+    private MediaType resolveMediaType(Object item) {
+        // all stream is presumed to be of items with same type
+        if (implicitMediaType == null) {
+            // unknown unwrapped objects are treated as json media type
+            implicitMediaType = IMPLICIT_MEDIA_TYPE.getOrDefault(item.getClass(), MediaType.APPLICATION_JSON_TYPE);
```
[the remark this answers is not in the document]
Comment (danielkec) [reply media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java]: 🤦 sorry, fixed

File: core-server/src/main/java/org/glassfish/jersey/server/ChunkedOutput.java [hunk 13]
```diff
@@ -287,6 +287,7 @@ public Void call() throws IOException {
             closed = true;
```
[the remark this answers is not in the document]
Comment (danielkec) [reply core-server/src/main/java/org/glassfish/jersey/server/ChunkedOutput.java:287]: updated

File: media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java [hunk 14]
```diff
@@ -39,55 +45,109 @@
...
         if (item == null) {
             throw new NullPointerException(LocalizationMessages.PARAM_NULL("outboundSseEvent"));
         }
         try {
-            write(item);
-        } catch (final IOException e) {
-            onError(e);
+            checkClosed();
+            MediaType implicitType = resolveMediaType(item);
+            if (MediaType.SERVER_SENT_EVENTS_TYPE == implicitType) {
```
[the remark this answers is not in the document]
Comment (danielkec) [reply media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java]: fixed

File: media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (danielkec) [reply media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java]: SEVERE it is

File: media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java (hunk 6 above)
Comment (danielkec) [reply media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java]: sure

File: media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java [hunk 15]
```diff
@@ -118,15 +158,38 @@ public void flush() throws IOException {
...
             throw new IllegalStateException(LocalizationMessages.EVENT_SOURCE_ALREADY_CLOSED());
         }
     }
+
+    private MediaType resolveMediaType(Object item) {
+        // all stream is presumed to be of items with same type
+        if (implicitMediaType == null) {
+            Class<?> clazz = item.getClass();
+            if (Number.class.isAssignableFrom(clazz)
+                    || Character.class.isAssignableFrom(clazz)
```
Comment (jansupol) [inline media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java:184]: Character, String and Boolean are final classes. Faster is just to compare them.

**Review by jansupol — CHANGES_REQUESTED** [review]

File: media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java (hunk 15 above)
Comment (danielkec) [reply media/sse/src/main/java/org/glassfish/jersey/media/sse/internal/JerseyEventSink.java]: My bad sorry

**Review by jansupol — APPROVED** [review]

**Comment by danielkec** [comment]
Sorry for the force push, conflicts solved ...

**Review by senivam — APPROVED** [review]
LGTM
