### PR TITLE
IPv6 support for http request

### LINKED ISSUE #5909: ipv6 request doesn't support
When I run the following program, I get an error. When add request header host,ipv6 request is not suport. The URL handling in the SSLParamConfigurator.toIPRequestUri() and SniConfigurator.createWhenHostHeader()  function doesn't seem to support IPv6. （jersey-client:3.1.10, jdk21）

```java
import jakarta.ws.rs.client.Client;
import jakarta.ws.rs.client.ClientBuilder;
import jakarta.ws.rs.core.HttpHeaders;
import jakarta.ws.rs.core.Response;
import org.glassfish.jersey.client.ClientProperties;

public class Test {
    public static void main(String[] args) {
        Client client = ClientBuilder.newClient();
        String u = "http://[172:30::333b]:8080/api/demo/v1";
        Response response = client.target(u)
                .request()
                .header(HttpHeaders.HOST, "[172:30::333b]:8080")
                .header("language-option-two", "true")
                .property(ClientProperties.CONNECT_TIMEOUT, 1800 * 1000)
                .property(ClientProperties.READ_TIMEOUT, 1800 * 1000)
                .get();
    }
}  

```

>  Exception in thread "main" jakarta.ws.rs.ProcessingException: java.net.UnknownHostException: 172%3A30%3A0%3A0%3A0%3A0%3A0%3A333b
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:288)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:300)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:674)
	at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:709)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:703)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:703)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:673)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:413)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:313)
	at com.zte.ums.zenap.base.RuntimeEnvService.main(RuntimeEnvService.java:73)
Caused by: java.net.UnknownHostException: 172%3A30%3A0%3A0%3A0%3A0%3A0%3A333b
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1304)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1052)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:453)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:286)

### PR DESCRIPTION
**Pull request by jansupol**

### CODE REVIEW

File: core-client/src/main/java/org/glassfish/jersey/client/innate/http/SSLParamConfigurator.java [hunk 1]
```diff
@@ -233,7 +234,13 @@ public URI toIPRequestUri() {
         String host = uri.getHost();
         try {
             InetAddress ip = InetAddress.getByName(host);
-            return UriBuilder.fromUri(uri).host(ip.getHostAddress()).build();
+            // ipv6 is expected in square brackets in UriBuilder#host() && `#isUriInetAddress()`
```
Comment (senivam) [inline core-client/src/main/java/org/glassfish/jersey/client/innate/http/SSLParamConfigurator.java]: the JDK itself should return `Inet6Address` in case it recognizes the IPv6 host. So, it could be enough to check
```
            if (ip instanceof Inet6Address) {
                return UriBuilder.fromUri(uri).build();
            }
```
or something like that...

**Review by senivam — APPROVED** [review]

**Review by jbescos — APPROVED** [review]

**Comment by Czytx** [comment]
The 3.0.x and 3.1.x branches have the same issue. Could you please fix them together?

**Comment by senivam** [comment]
@Czytx, sure, it will be ported from the 2.x to both branches
